version: '3.8'
services:
  catalog:
    build: ./src/CatalogService
    ports:
      - "5101:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  auction:
    build: ./src/AuctionService
    ports:
      - "5102:80"
  order:
    build: ./src/OrderService
    ports:
      - "5103:80"
  transaction:
    build: ./src/TransactionService
    ports:
      - "5104:80"
  user:
    build: ./src/UserService
    ports:
      - "5105:80"
  ui:
    build: ./src/ui-angular
    ports:
      - "4200:80"
    depends_on:
      - user
      - catalog
      - order
      - transaction
      - auction
