services:

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - userservice
      - orderservice
    networks:
      - docker_demo

  userservice:
    build:
      context: ./services/userservice/UserService
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=UserDb;User=sa;Password=YourStrong!Passw0rd2026;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      docker_demo:
        aliases:
          - userservice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  productservice:
    build:
      context: ./services/productservice/ProductService
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=ProductDb;User=sa;Password=YourStrong!Passw0rd2026;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      docker_demo:
        aliases:
          - productservice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  orderservice:
    build:
      context: ./services/orderservice/OrderService
      dockerfile: Dockerfile
    restart: unless-stopped
    
    depends_on:
      userservice:
        condition: service_started
      productservice:
        condition: service_started
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=sqlserver;Database=OrderDb;User=sa;Password=YourStrong!Passw0rd2026;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      docker_demo:
        aliases:
          - orderservice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd2026
      - ACCEPT_EULA=Y
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - docker_demo
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sql_data:

networks:
  docker_demo:
